MODEL:
  TYPE: restormer
  NAME: pretrain
  DROP_PATH_RATE: 0.0
  RECOVER_TARGET_TYPE: m_masked #m_m_masked # # masked  #
  BATCH_SIZE: 6
  RESTORMER:
    INP_CHANNELS: 3
    OUT_CHANNELS: 64
    DIM: 48
    NUM_BLOCKS: [4,6,6,8]
    NUM_REFINEMENT_BLOCKS: 4
    HEADS: [1,2,4,8]
    FFN_EXPANSION_FACTOR: 2.66
    BIAS: False
    LAYERNORM_TYPE: WithBias
    DUAL_PIXEL_TASK: False
    GLOBAL_RESIDUAL: False
    PATCH_SIZE : 1
  DECODER:
    IN_NC: 64
    OUT_NC: 3
    UPSCALE: 1


    MODUL_CHANNELS: 512
    REQUIRE_MODULATION: false
    MODULATION_MODE: GFM

DATA:
  IMG_SIZE: 224
  FILTER_TYPE: IFP
  SAMPLE_RATIO: 0.5
  MASK_RADIUS1: 16
  MASK_RADIUS2: 999
TRAIN:
  EPOCHS: 60000
  WARMUP_EPOCHS: 20
  BASE_LR: 3e-4
  WARMUP_LR: 2.5e-7
  MIN_LR: 2.5e-6
  WEIGHT_DECAY: 0.05
  CLIP_GRAD: 3.0
  OPTIMIZER:
    BETAS: (0.9, 0.95)
PRINT_FREQ: 300
SAVE_FREQ: 300
TAG: IFP_restormer_possNoise_M75Masked_gt224_size1_60000ep