MODEL:
  TYPE: uformer
  NAME: pretrain
  DROP_PATH_RATE: 0.0
  RECOVER_TARGET_TYPE: m_masked # masked  #
  BATCH_SIZE: 1
  UFORMER:
    INP_CHANNELS: 3
    IMAGE_SIZE : 256
    PATCH_SIZE : 1


DATA:
  IMG_SIZE: 256
  FILTER_TYPE: IFP
  SAMPLE_RATIO: 0.5
  MASK_RADIUS1: 16
  MASK_RADIUS2: 999
TRAIN:
  EPOCHS: 60000
  WARMUP_EPOCHS: 20
  BASE_LR: 3e-4
  WARMUP_LR: 2.5e-7
  MIN_LR: 2.5e-6
  WEIGHT_DECAY: 0.05
  CLIP_GRAD: 3.0
  OPTIMIZER:
    BETAS: (0.9, 0.95)
PRINT_FREQ: 300
SAVE_FREQ: 300
TAG: IFP__uformer_M75Masked_gt256_60000ep      
